### ISSUE TITLE
Copy edit

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/physical-computing-with-python#1]
Hi @lauraclay and @LornaLynch,
Could I get a copy edit on this please. Some of it is new content, but most is taken from other resources, so might just need a 'light' going over.
The idea is to replace Physical Computing Guide, Getting started with gpiozero and CamJam1 resources, with this one.

**Comment by lauraclay** [comment]
All done!

**Comment by Tom-Archer** [comment]
Sorry to leave a comment here, but just wondering what program you use to make your lovely circuit diagrams? I'm looking to put some tutorials together with a similar style. It looks like a Fritzing diagram at first look, but your parts don't look like the ones that come with it? Cheers,

**Comment by MarcScott** [comment]
We have a designer who makes them base off our Fritzing diagrams.

**Comment by Tom-Archer** [comment]
Ah, thanks for that.
