### ISSUE TITLE
Making a switch example doesn't work well

### ISSUE THREAD

**Issue by DaddyTheRunner** [raspberrypilearning/physical-computing-with-python#13]
The [Making a switch](https://github.com/raspberrypilearning/physical-computing-with-python/blob/master/worksheet.md#making-a-switch) example does not work well.  I think it is due to switch de-bounce issues related to the `button.wait_for_press` function.  I've filed a separate [issue](https://github.com/RPi-Distro/python-gpiozero/issues/550) in the `gpiozero` repo to see if that issue can be resolved.

Until the `button.wait_for_press` function issue is resolved in  `gpiozero`, I recommend using the following code in the lesson which is more reliable:

```python
from gpiozero import LED, Button
from signal import pause

led = LED(17)
button = Button(2)

button.when_pressed = led.toggle

pause()
```

Admittedly, it would be nice to keep the `while` loop for educational purposes.  So, if that is more important, I would recommend adding a "manual" de-bounce to the original sample code:

```python
from gpiozero import LED, Button
from time import sleep

led = LED(17)
button = Button(2)

while True:
    button.wait_for_press()
    led.toggle()
    sleep(1)
```

Either one of these options creates a more reliable toggle switch example.

**Comment by lawsie** [comment]
@bennuttall @MarcScott

**Comment by bennuttall** [comment]
I think the procedural style is better here, i.e. the `while True`. I've never had a problem with bounce time myself but heard the very occasional issue. Adding a small sleep should help without causing issues for people.
