### ISSUE TITLE
Copy editing distance page

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/physical-computing-with-python#3]
Hi @LornaLynch & @lauraclay, can one of you please copy edit the [distance.md](https://github.com/raspberrypilearning/physical-computing-with-python/blob/distancesensor/distance.md) file in the **distancesensor** branch so @MarcScott can merge PR #2 when he's happy with it?

_I'm a little happy at being able to assign two people to the same issue_

:)

**Comment by LornaLynch** [comment]
On it now.

**Comment by LornaLynch** [comment]
All done. I'll leave it to @MarcScott to merge as requested above.

**Comment by bennuttall** [comment]
Thanks @LornaLynch

**Comment by lauraclay** [comment]
Changing a few things as per the style guide - please don't merge until I've closed the issue.
