### ISSUE TITLE
Copy editing motors page

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/physical-computing-with-python#5]
@LornaLynch @lauraclay I've created another branch with a new page about motors. Can you please copy edit the [motors.md](https://github.com/raspberrypilearning/physical-computing-with-python/blob/motors/motors.md) file in the **motors** branch?

Re: PR #4 @MarcScott 

Thanks

**Comment by LornaLynch** [comment]
Just a note: the image links aren't working, but I'm guessing that is because this is not the main branch?

**Comment by LornaLynch** [comment]
Done barring the query above. @MarcScott do you want to merge?

**Comment by bennuttall** [comment]
Thanks @LornaLynch. I haven't created the images yet, so they'll need to be added before it gets merged.

**Comment by lauraclay** [comment]
There are further edits I'd like to make on this and the other page today (a few American spellings, for instance), so please hold off on merging.

Also, it'd be helpful if requests to edit didn't come in at weekends before one of us has a chance to look at them. Ta!.

**Comment by LornaLynch** [comment]
Sorry @lauraclay: I missed the American spellings.

**Comment by lauraclay** [comment]
Leave a comment
