### ISSUE TITLE
Wiring diagrams for MCP3008 are incorrect

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/physical-computing-with-python#7]
It's just been brought to my attention that the wiring diagrams for the MCP3008 are incorrect.

Here is a correct one: 

![mcp3008](https://cloud.githubusercontent.com/assets/1609725/17806938/6669a9de-65ff-11e6-89ac-ba6eae2bd1dc.png)

It's the four coloured wired in the middle of the chip that are wrong.

@samalderhyde can you change the wiring of the MCP3008 in each of the diagrams? Send them to me and I'll reupload them. Thanks.

**Comment by samalderhyde** [comment]
No problem - can fix this first thing Wednesday
