### ISSUE TITLE
Missing components

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/physical-computing-with-python#8]
Components from new worksheets missing - and some missing from older worksheets.

**Comment by DeeJay** [comment]
Little Yellow Motors are required for the Motors worksheet but are not listed in the hardware requirements.

Has resulted in the following Raspberry Pi forum query: [https://www.raspberrypi.org/forums/viewtopic.php?f=37&t=173777#p1110776]( https://www.raspberrypi.org/forums/viewtopic.php?f=37&t=173777#p1110776 )

**Comment by mrichardson23** [comment]
Is this the same issue? https://twitter.com/EfrenR/status/843168702996660224

**Comment by MarcScott** [comment]
Looks like a different issue, but has now been resolved

**Comment by MarcScott** [comment]
Added most components now - awaiting design for pot and mcp3008

**Comment by MarcScott** [comment]
resource archived - closing
